"""
PCB Builder - Gerber Generation Service
Production-grade Gerber/NC Drill/BOM export using KiCad CLI.
"""

import json
import shutil
import subprocess
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from shared.config import get_settings
from shared.logging_config import logger
from shared.models import Design

settings = get_settings()


class GerberGenerator:
    """Generates fabrication output files from a KiCad PCB design."""

    # Standard Gerber layer names
    GERBER_LAYERS = {
        "F_Cu": "Top Copper",
        "B_Cu": "Bottom Copper",
        "F_Mask": "Top Solder Mask",
        "B_Mask": "Bottom Solder Mask",
        "F_SilkS": "Top Silkscreen",
        "B_SilkS": "Bottom Silkscreen",
        "F_Paste": "Top Paste",
        "B_Paste": "Bottom Paste",
        "Edge_Cuts": "Board Outline",
    }

    def __init__(self):
        self.kicad_cli = "kicad-cli"

    def generate_all(
        self,
        kicad_pcb_path: Path,
        output_dir: Path,
        board_config: Optional[dict] = None,
    ) -> dict:
        """Generate all fabrication files."""
        output_dir.mkdir(parents=True, exist_ok=True)
        results = {
            "gerber_layers": [],
            "drill_files": [],
            "bom": None,
            "pick_place": None,
            "fabrication_drawing": None,
            "errors": [],
        }

        # Generate Gerbers
        gerber_dir = output_dir / "gerber"
        gerber_dir.mkdir(exist_ok=True)
        try:
            gerber_layers = self._generate_gerbers(kicad_pcb_path, gerber_dir)
            results["gerber_layers"] = gerber_layers
        except Exception as e:
            results["errors"].append(f"Gerber generation failed: {e}")
            logger.error("Gerber generation failed", error=str(e))

        # Generate drill files
        drill_dir = output_dir / "drill"
        drill_dir.mkdir(exist_ok=True)
        try:
            drill_files = self._generate_drill(kicad_pcb_path, drill_dir)
            results["drill_files"] = drill_files
        except Exception as e:
            results["errors"].append(f"Drill generation failed: {e}")

        # Generate pick-and-place
        try:
            pos_file = self._generate_pick_place(kicad_pcb_path, output_dir)
            results["pick_place"] = str(pos_file) if pos_file else None
        except Exception as e:
            results["errors"].append(f"Pick-and-place generation failed: {e}")

        # Generate fabrication drawing (PDF)
        try:
            pdf_file = self._generate_pdf(kicad_pcb_path, output_dir)
            results["fabrication_drawing"] = str(pdf_file) if pdf_file else None
        except Exception as e:
            results["errors"].append(f"PDF generation failed: {e}")

        return results

    def _generate_gerbers(self, pcb_path: Path, output_dir: Path) -> list[str]:
        """Generate Gerber files for all layers."""
        try:
            result = subprocess.run(
                [
                    self.kicad_cli, "pcb", "export", "gerbers",
                    "--output", str(output_dir),
                    str(pcb_path),
                ],
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode != 0:
                raise RuntimeError(f"KiCad CLI error: {result.stderr}")

            # List generated files
            files = [f.name for f in output_dir.glob("*.gbr")]
            logger.info("Gerber files generated", count=len(files), files=files)
            return files

        except FileNotFoundError:
            logger.warning("KiCad CLI not found, using fallback Gerber generation")
            return self._generate_fallback_gerbers(output_dir)

    def _generate_fallback_gerbers(self, output_dir: Path) -> list[str]:
        """Generate minimal Gerber files if KiCad CLI unavailable."""
        files = []
        for layer_code, layer_name in self.GERBER_LAYERS.items():
            filename = f"design-{layer_code}.gbr"
            filepath = output_dir / filename
            content = f"G04 Generated by XgenPCB - {layer_name}*\n"
            content += "%FSLAX35Y35*%\n"
            content += "%MOMM*%\n"
            content += "%LPD*%\n"
            content += "M02*\n"
            filepath.write_text(content)
            files.append(filename)
        return files

    def _generate_drill(self, pcb_path: Path, output_dir: Path) -> list[str]:
        """Generate NC drill files."""
        try:
            result = subprocess.run(
                [
                    self.kicad_cli, "pcb", "export", "drill",
                    "--output", str(output_dir),
                    str(pcb_path),
                ],
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode != 0:
                raise RuntimeError(f"KiCad CLI error: {result.stderr}")

            files = [f.name for f in output_dir.glob("*.drl")]
            return files

        except FileNotFoundError:
            logger.warning("KiCad CLI not found, using fallback drill")
            return self._generate_fallback_drill(output_dir)

    def _generate_fallback_drill(self, output_dir: Path) -> list[str]:
        """Generate minimal drill file."""
        filepath = output_dir / "design.drl"
        content = "M48\nMETRIC\nT01C0.3\n%\nT01\nX0Y0\nM30\n"
        filepath.write_text(content)
        return ["design.drl"]

    def _generate_pick_place(self, pcb_path: Path, output_dir: Path) -> Optional[Path]:
        """Generate pick-and-place file."""
        try:
            result = subprocess.run(
                [
                    self.kicad_cli, "pcb", "export", "pos",
                    "--output", str(output_dir / "design-pos.csv"),
                    str(pcb_path),
                ],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode == 0:
                return output_dir / "design-pos.csv"
            return None
        except FileNotFoundError:
            return None

    def _generate_pdf(self, pcb_path: Path, output_dir: Path) -> Optional[Path]:
        """Generate fabrication drawing PDF."""
        try:
            result = subprocess.run(
                [
                    self.kicad_cli, "pcb", "export", "pdf",
                    "--output", str(output_dir / "design-fab.pdf"),
                    str(pcb_path),
                ],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode == 0:
                return output_dir / "design-fab.pdf"
            return None
        except FileNotFoundError:
            return None

    def create_zip_package(
        self,
        output_dir: Path,
        design_name: str,
        board_config: dict,
        validation_report: Optional[dict] = None,
    ) -> Path:
        """Create a complete fabrication zip package with README."""
        zip_path = output_dir / f"{design_name}-fab.zip"

        # Generate README
        readme = self._generate_readme(design_name, board_config, validation_report)
        readme_path = output_dir / "README.txt"
        readme_path.write_text(readme)

        # Create zip
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for f in output_dir.rglob("*"):
                if f == zip_path:
                    continue
                arcname = f.relative_to(output_dir)
                zf.write(f, arcname)

        return zip_path

    def _generate_readme(
        self,
        design_name: str,
        board_config: dict,
        validation_report: Optional[dict],
    ) -> str:
        """Generate fabrication README."""
        lines = [
            "=" * 60,
            f"FABRICATION PACKAGE: {design_name}",
            "=" * 60,
            f"Generated: {datetime.now(timezone.utc).isoformat()}",
            "Generated by: XgenPCB AI Platform",
            "",
            "BOARD SPECIFICATIONS:",
            f"  Size: {board_config.get('width_mm', 0)} x {board_config.get('height_mm', 0)} mm",
            f"  Layers: {board_config.get('layers', 2)}",
            f"  Thickness: {board_config.get('thickness_mm', 1.6)} mm",
            f"  Material: {board_config.get('material', 'FR4')}",
            f"  Surface Finish: {board_config.get('surface_finish', 'HASL')}",
            f"  Copper Weight: {board_config.get('copper_weight', '1oz')}",
            "",
            "FILE CONTENTS:",
            "  gerber/      - Gerber RS-274X files per layer",
            "  drill/       - NC Excellon drill files",
            "  design-pos.csv - Pick-and-place file",
            "  design-fab.pdf - Fabrication drawing",
            "",
        ]

        if validation_report:
            lines.extend([
                "VALIDATION RESULTS:",
                f"  DRC Score: {validation_report.get('drc', {}).get('score', 'N/A')}/100",
                f"  DFM Score: {validation_report.get('dfm', {}).get('score', 'N/A')}/100",
                f"  SI Score: {validation_report.get('si', {}).get('score', 'N/A')}/100",
                f"  Ready for Fab: {'YES' if validation_report.get('ready_for_fab') else 'NO'}",
                "",
            ])

        lines.extend([
            "MANUFACTURING NOTES:",
            "  - All units in millimeters",
            "  - Board origin at bottom-left corner",
            "  - All copper layers positive",
            "  - Drill files in Excellon format",
            "",
            "CONTACT:",
            "  For issues, contact support@xgenpcb.ai",
            "=" * 60,
        ])

        return "\n".join(lines)


def generate_fabrication_package(
    design: Design,
    output_dir: Path,
    validation_report: Optional[dict] = None,
) -> dict:
    """Generate complete fabrication package for a design."""
    gen = GerberGenerator()

    # Create KiCad file first
    from services.eda_service.routes import write_kicad_board

    with tempfile.TemporaryDirectory() as tmpdir:
        project_path = Path(tmpdir) / "design"
        project_path.mkdir()

        kicad_path = write_kicad_board(
            project_path,
            design.board_config,
            design.pcb_layout,
            title=design.name,
        )

        # Generate all outputs
        results = gen.generate_all(kicad_path, output_dir, design.board_config)

        # Create zip
        if not results["errors"]:
            zip_path = gen.create_zip_package(
                output_dir,
                design.name,
                design.board_config,
                validation_report,
            )
            results["zip_path"] = str(zip_path)

        return results
