"""
PCB Builder - EDA Service Routes
KiCad integration, DRC engine, Gerber generation, 3D model export.
"""

import asyncio
import json
import shutil
import subprocess
import tempfile
import uuid
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from shared.config import get_settings
from shared.database import get_db
from shared.middleware.auth import get_current_user
from shared.middleware.rate_limit import limiter
from shared.models import Component, Design, Job, User
from shared.schemas import ComponentResponse, ComponentSearch, DRCRequest, DRCResult, JobResponse

settings = get_settings()
router = APIRouter()


def write_kicad_schematic(project_dir: Path, schematic_data: dict) -> Path:
    """Convert JSON schematic to KiCad .kicad_sch format."""
    sch_path = project_dir / "design.kicad_sch"
    # KiCad S-expression format
    components = schematic_data.get("components", [])
    nets = schematic_data.get("nets", [])

    sexp = "(kicad_sch (version 20231120) (generator pcb_builder)\n"
    sexp += '  (paper "A4")\n'

    for comp in components:
        sexp += f'  (symbol (lib_id "{comp.get("lib_id", "Device:R")}") '
        sexp += f'(at {comp.get("x", 0)} {comp.get("y", 0)}) '
        sexp += f'(uuid "{comp.get("id", str(uuid.uuid4()))}"))\n'

    sexp += ")\n"
    sch_path.write_text(sexp)
    return sch_path


def write_kicad_board(project_dir: Path, board_config: dict, pcb_layout: dict = None, title: str = "XgenPCB Design") -> Path:
    """Convert JSON board config to KiCad .kicad_pcb format."""
    from datetime import datetime
    
    pcb_path = project_dir / "design.kicad_pcb"
    width = board_config.get("width_mm", 100)
    height = board_config.get("height_mm", 100)
    layers = board_config.get("layers", 2)

    sexp = "(kicad_pcb (version 20231014) (generator xgenpcb)\n"
    sexp += f"  (general (thickness {board_config.get('thickness_mm', 1.6)})\n"
    sexp += f"    (board {width} {height} 0 0)\n"
    sexp += f'    (title "{title}")\n'
    sexp += f'    (date "{datetime.now().isoformat()}")\n'
    sexp += '    (comment 1 "Generated by XgenPCB AI")\n'
    sexp += '  )\n'

    # Layer definitions - KiCad 9 compatible
    sexp += "  (layers\n"
    sexp += '    (0 "F.Cu" signal)\n'
    if layers >= 4:
        sexp += '    (1 "In1.Cu" signal)\n'
        sexp += '    (2 "In2.Cu" signal)\n'
    if layers >= 6:
        sexp += '    (3 "In3.Cu" signal)\n'
        sexp += '    (4 "In4.Cu" signal)\n'
    sexp += '    (31 "B.Cu" signal)\n'
    sexp += '    (32 "B.Adhes" user)\n'
    sexp += '    (33 "F.Adhes" user)\n'
    sexp += '    (34 "B.Paste" user)\n'
    sexp += '    (35 "F.Paste" user)\n'
    sexp += '    (36 "B.SilkS" user)\n'
    sexp += '    (37 "F.SilkS" user)\n'
    sexp += '    (38 "B.Mask" user)\n'
    sexp += '    (39 "F.Mask" user)\n'
    sexp += '    (40 "Edge.Cuts" user)\n'
    sexp += '    (41 "Margin" user)\n'
    sexp += '    (42 "F.CrtYd" user)\n'
    sexp += '    (43 "B.CrtYd" user)\n'
    sexp += '    (44 "F.Fab" user)\n'
    sexp += '    (45 "B.Fab" user)\n'
    sexp += "  )\n"

    # Net definitions
    net_names = set()
    if pcb_layout:
        for track in pcb_layout.get("tracks", []):
            if track.get("net"):
                net_names.add(track["net"])
    
    if net_names:
        for idx, net_name in enumerate(sorted(net_names)):
            sexp += f'  (net {idx+1} "{net_name}")\n'
    else:
        sexp += '  (net 0 "")\n'

    # Board outline
    sexp += f"  (gr_rect (start 0 0) (end {width} {height}) (layer Edge.Cuts) (width 0.15))\n"

    # Add placed components
    if pcb_layout:
        for comp in pcb_layout.get("placed_components", []):
            footprint = comp.get("footprint", "Unknown")
            
            # ── Universal Library Resolver (30k+ Footprints) ──────
            try:
                index_path = Path("/app/footprints_index.json")
                if index_path.exists():
                    with open(index_path, "r") as f:
                        fp_index = json.load(f)
                        
                        # Normalize and extract part name
                        full_name = footprint
                        part_name = footprint.split(":")[-1] if ":" in footprint else footprint
                        query_tokens = set(part_name.lower().replace("_", "-").split("-"))
                        
                        # 1. Exact check: Does the current name exist as a valid value?
                        if full_name not in fp_index.values():
                            # 2. Search index for best match using token scoring
                            best_match = None
                            max_score = 0
                            
                            for key, val in fp_index.items():
                                # key is the normalized hyphenated name (e.g. "terminalblock-phoenix-pt-2pin")
                                key_tokens = set(key.split("-"))
                                overlap = len(query_tokens.intersection(key_tokens))
                                
                                # Scoring: Favor exact matches, then high overlap
                                if overlap > max_score:
                                    max_score = overlap
                                    best_match = val
                                    
                            if best_match and max_score >= 1:
                                footprint = best_match
                                print(f"DEBUG: Fuzzy resolved '{part_name}' to '{footprint}' (Score: {max_score})")
                else:
                    print("DEBUG: Footprint index not found. Skipping resolution.")
            except Exception as e:
                print(f"Index search error: {e}")
            # ──────────────────────────────────────────────────────
            
            x = comp.get("x", 0)
            y = comp.get("y", 0)
            rotation = comp.get("rotation", 0)
            layer = comp.get("layer", "F")
            name = comp.get("name", comp.get("id", ""))
            mpn = comp.get("mpn", "")
            sexp += f'  (footprint "{footprint}"\n'
            sexp += f'    (at {x} {y} {rotation})\n'
            sexp += f'    (layer {layer}.Cu)\n'
            sexp += f'    (property "Reference" "{name}")\n'
            sexp += f'    (property "Value" "{mpn}")\n'
            sexp += "  )\n"

        for i, track in enumerate(pcb_layout.get("tracks", [])):
            start = track.get("start", [0, 0])
            end = track.get("end", [0, 0])
            width_t = track.get("width", 0.25)
            layer_t = track.get("layer", "F.Cu")
            net_idx = 0
            if track.get("net"):
                net_list = sorted(net_names)
                if track["net"] in net_list:
                    net_idx = net_list.index(track["net"]) + 1
            sexp += f"  (segment (start {start[0]} {start[1]}) (end {end[0]} {end[1]})\n"
            sexp += f"    (width {width_t})\n"
            sexp += f'    (layer "{layer_t}")\n'
            sexp += f'    (net {net_idx}))\n'

        for via in pcb_layout.get("vias", []):
            x = via.get("x", 0)
            y = via.get("y", 0)
            size = via.get("diameter", 0.6)
            sexp += f"  (via (at {x} {y}) (size {size}) (drill 0.3)\n"
            sexp += f"    (layers 0 31)\n"
            sexp += "  )\n"

    sexp += ")\n"
    pcb_path.write_text(sexp)
    return pcb_path


def parse_drc_output(output: str) -> list[dict]:
    """Parse KiCad DRC output into structured violations."""
    violations = []
    for line in output.strip().split("\n"):
        if not line.strip():
            continue
        # Simplified DRC output parsing
        if "Error" in line or "Warning" in line:
            severity = "error" if "Error" in line else "warning"
            violations.append({
                "type": "clearance" if "clearance" in line.lower() else "generic",
                "severity": severity,
                "message": line.strip(),
                "location": {"x": 0, "y": 0},
            })
    return violations


# ━━ DRC ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@router.post("/drc", response_model=DRCResult)
async def run_drc(
    request: DRCRequest,
    current_user: User = Depends(get_current_user),
):
    """Run Design Rule Check on a PCB design."""
    with tempfile.TemporaryDirectory() as tmpdir:
        project_path = Path(tmpdir) / "design"
        project_path.mkdir()

        # ── Footprint Library Link ──────────────────────────
        global_table = Path("/app/fp-lib-table")
        if global_table.exists():
            shutil.copy(global_table, project_path / "fp-lib-table")
        # ──────────────────────────────────────────────────

        board_config = request.design_data.get("board_config", {})
        pcb_layout = request.design_data.get("pcb_layout", {})

        write_kicad_board(project_path, board_config, pcb_layout)

        # Try running KiCad CLI DRC
        try:
            result = await asyncio.create_subprocess_exec(
                "kicad-cli", "pcb", "drc",
                "--output", str(project_path / "drc_report.json"),
                "--format", "json",
                str(project_path / "design.kicad_pcb"),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(result.communicate(), timeout=60)

            # Parse report
            report_path = project_path / "drc_report.json"
            if report_path.exists():
                report = json.loads(report_path.read_text())
                violations = report.get("violations", [])
            else:
                violations = parse_drc_output(stdout.decode())

        except FileNotFoundError:
            # KiCad CLI not installed - run built-in checks
            violations = _builtin_drc(board_config, pcb_layout, request.rules)
        except asyncio.TimeoutError:
            raise HTTPException(status_code=504, detail="DRC timed out")

    warnings = [v for v in violations if v.get("severity") == "warning"]
    errors = [v for v in violations if v.get("severity") == "error"]
    score = max(0.0, 1.0 - (len(errors) * 0.1) - (len(warnings) * 0.02))

    return DRCResult(
        violations=violations,
        warnings=warnings,
        score=round(score, 2),
        passed=len(errors) == 0,
    )


# ━━ Download KiCad PCB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@router.get("/download/{design_id}")
async def download_kicad(
    design_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download the .kicad_pcb file for a design."""
    from sqlalchemy import select

    result = await db.execute(select(Design).where(Design.id == design_id))
    design = result.scalar_one_or_none()
    if not design:
        raise HTTPException(status_code=404, detail="Design not found")

    # Try to read from stored file first
    file_content = None
    filename = f"{design.name}.kicad_pcb"

    if design.local_path:
        file_path = Path(design.local_path)
        if file_path.exists():
            file_content = file_path.read_text()

    # Fallback: regenerate from DB stored data
    if not file_content:
        with tempfile.TemporaryDirectory() as tmpdir:
            project_path = Path(tmpdir) / "design"
            project_path.mkdir()
            kicad_path = write_kicad_board(project_path, design.board_config, design.pcb_layout)
            file_content = kicad_path.read_text()

    from fastapi.responses import Response

    return Response(
        content=file_content,
        media_type="application/octet-stream",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


def _builtin_drc(board_config: dict, pcb_layout: dict, rules: dict) -> list[dict]:
    """Built-in DRC when KiCad CLI is not available."""
    violations = []
    min_trace = rules.get("min_trace_mm", 0.15)
    min_clearance = rules.get("min_clearance_mm", 0.15)
    min_via = rules.get("min_via_mm", 0.3)

    tracks = pcb_layout.get("tracks", [])
    for track in tracks:
        if track.get("width", 0.25) < min_trace:
            violations.append({
                "type": "trace_width",
                "severity": "error",
                "message": f"Trace width {track['width']}mm below minimum {min_trace}mm",
                "location": {"x": track.get("start", [0, 0])[0], "y": track.get("start", [0, 0])[1]},
            })

    components = pcb_layout.get("placed_components", [])
    for i, comp_a in enumerate(components):
        for comp_b in components[i + 1:]:
            dx = abs(comp_a.get("x", 0) - comp_b.get("x", 0))
            dy = abs(comp_a.get("y", 0) - comp_b.get("y", 0))
            dist = (dx**2 + dy**2) ** 0.5
            if dist < min_clearance:
                violations.append({
                    "type": "clearance",
                    "severity": "error",
                    "message": f"Clearance violation between components ({dist:.2f}mm < {min_clearance}mm)",
                    "location": {"x": comp_a.get("x", 0), "y": comp_a.get("y", 0)},
                })

    return violations


# ━━ Gerber Generation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@router.post("/generate-gerber")
@limiter.limit("10/minute")
async def generate_gerber(
    request: Request,
    design_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Generate Gerber files for fabrication (queued as Celery task)."""
    result = await db.execute(select(Design).where(Design.id == design_id))
    design = result.scalar_one_or_none()
    if not design:
        raise HTTPException(status_code=404, detail="Design not found")

    job_id = uuid.uuid4()
    job = Job(
        id=job_id,
        user_id=current_user.id,
        job_type="gerber_generation",
        status="queued",
        progress=0.0,
        input_data={"design_id": str(design_id)},
        stage="queued",
        retries=0,
        max_retries=2,
    )
    db.add(job)
    await db.commit()

    from services.eda_service.tasks import generate_gerber_task
    generate_gerber_task.delay(str(job_id), str(design_id))

    return {
        "job_id": str(job_id),
        "status": "queued",
        "message": "Gerber generation queued",
        "links": {
            "self": f"/api/v1/ai/jobs/{job_id}",
        },
    }


@router.get("/job/{job_id}", response_model=JobResponse)
async def get_job_status(
    job_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Check status of an async job from database."""
    result = await db.execute(select(Job).where(Job.id == job_id))
    job = result.scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if job.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")
    return JobResponse.model_validate(job)


# ━━ Component Search ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

@router.post("/components/search", response_model=list[ComponentResponse])
async def search_components(
    search: ComponentSearch,
    db: AsyncSession = Depends(get_db),
):
    """Search component library."""
    from sqlalchemy import select, or_

    query = select(Component)

    if search.query:
        query = query.where(
            or_(
                Component.name.ilike(f"%{search.query}%"),
                Component.mpn.ilike(f"%{search.query}%"),
                Component.description.ilike(f"%{search.query}%"),
            )
        )
    if search.category:
        query = query.where(Component.category == search.category)
    if search.manufacturer:
        query = query.where(Component.manufacturer.ilike(f"%{search.manufacturer}%"))
    if search.package_type:
        query = query.where(Component.package_type == search.package_type)

    query = query.offset(search.offset).limit(search.limit)
    result = await db.execute(query)
    components = result.scalars().all()

    return [ComponentResponse.model_validate(c) for c in components]
